01. List manipulation

In [44]:
from random import shuffle

# a) Create a list with 5 fruit names
fruit_names = ["orange", "banana", "strawberry", "pear", "grape"]

# b) Extend the fruit_names list with 2 vegatables
fruit_names.append("cucumber")
fruit_names.append("tomato")

print(fruit_names)
# c) Shuffle the list
shuffle(fruit_names)
print(fruit_names)

# d) Find the position of first vegetable 
for i in fruit_names:
  if i == "cucumber" or i == "tomato":
    print("First veg:", fruit_names.index(i), i)
    break


# e) Remove one fruit
for i in fruit_names:
  if i != "cucumber" or i != "tomato":
    print("Deleting:", fruit_names.index(i), i)
    fruit_names.pop(fruit_names.index(i))
    break



# f) Print the result
print(fruit_names)

# g) Sort the list in alphabetical order
fruit_names_sorted = sorted(fruit_names)

# h) Print each element of a list using a loop
for i in fruit_names_sorted:
  print(i)

# i) Modify above code to be ablet to repeat all above steps 
#    to get the same results each time

['orange', 'banana', 'strawberry', 'pear', 'grape', 'cucumber', 'tomato']
['orange', 'grape', 'banana', 'tomato', 'strawberry', 'cucumber', 'pear']
First veg: 3 tomato
Deleting: 0 orange
['grape', 'banana', 'tomato', 'strawberry', 'cucumber', 'pear']
banana
cucumber
grape
pear
strawberry
tomato

02. Tuples

In [45]:
first_list = ["a" + str(number) for number in range(1, 10)]
second_list = ["b" + str(number) for number in range(1, 10)]

print(first_list)
print(second_list)

# Pair up above lists
tmp = []
for i in range(0, len(first_list)):
  tupl = (first_list[i], second_list[i])
  tmp.append(tupl)
paired_list = tmp

print(paired_list)


# Using a loop unpack the tuple into variables: first_el, secodn_el
# Print the pair position and variables using f-string.
for i in range(0, len(paired_list)):
  first_el = paired_list[i][0]
  second_el = paired_list[i][1]

  print(f"Infex of {first_el} and {second_el} is equal {i}")

['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9']
['b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9']
[('a1', 'b1'), ('a2', 'b2'), ('a3', 'b3'), ('a4', 'b4'), ('a5', 'b5'), ('a6', 'b6'), ('a7', 'b7'), ('a8', 'b8'), ('a9', 'b9')]
Infex of a1 and b1 is equal 0
Infex of a2 and b2 is equal 1
Infex of a3 and b3 is equal 2
Infex of a4 and b4 is equal 3
Infex of a5 and b5 is equal 4
Infex of a6 and b6 is equal 5
Infex of a7 and b7 is equal 6
Infex of a8 and b8 is equal 7
Infex of a9 and b9 is equal 8

3. Sets (unordered & unique data)

In [46]:
fake_names_1 = ['Sherry', 'Mary', 'Matthew', 'Danielle', 'Jeffrey', 'Lauren', 
              'Keith', 'Carlos', 'Monique', 'Laura', 'Jared', 'Valerie', 'Juan', 
              'Christopher', 'Erica', 'Dawn', 'Joshua', 'Brandon', 'Stephanie']

fake_names_2 = ['Andre', 'Anthony', 'Lauren', 'Douglas', 'Jonathan', 'Richard', 
                'Alyssa', 'Vincent', 'Travis', 'Clifford', 'Jerry', 'Justin',
                'Matthew', 'Jared', 'Erica']

# Find the overlapping names in above lists
# Print number of "duplicated" names
duplicates = 0

for i in range(0, len(fake_names_1)):
  if fake_names_1[i] in fake_names_2:
    print("Overlapping name:", fake_names_1[i])
    duplicates += 1

print("Duplicated:", duplicates)

# Find and print the union of above lists
uni = list(set().union(fake_names_1, fake_names_2))
print(uni)

# Find and print the difference between lists
diff = list(set(fake_names_1) - set(fake_names_2))
print(diff)

Overlapping name: Matthew
Overlapping name: Lauren
Overlapping name: Jared
Overlapping name: Erica
Duplicated: 4
['Stephanie', 'Andre', 'Juan', 'Laura', 'Clifford', 'Dawn', 'Monique', 'Sherry', 'Alyssa', 'Vincent', 'Richard', 'Erica', 'Travis', 'Jonathan', 'Danielle', 'Jared', 'Lauren', 'Jerry', 'Brandon', 'Valerie', 'Mary', 'Joshua', 'Matthew', 'Jeffrey', 'Justin', 'Carlos', 'Anthony', 'Douglas', 'Christopher', 'Keith']
['Stephanie', 'Monique', 'Jeffrey', 'Juan', 'Danielle', 'Carlos', 'Laura', 'Brandon', 'Valerie', 'Dawn', 'Mary', 'Christopher', 'Keith', 'Sherry', 'Joshua']